Readme fixes
nuvolaris/openserverless pull request #2
Opened 2024-07-06 18:10 UTC by giusdp

2024-07-06 21:31 UTC, d4rkstar requested changes

2024-07-06 21:31 UTC, d4rkstar commented on README.md
> +If you do not want to keep the VM anymore, esure you have backed up all your files. Then remove it in your cloud provider (check your cloud provider documentation).
It should be "ensure"

2024-07-06 21:31 UTC, d4rkstar commented on README.md
>  - fork a subproject: for example `github.com/apache/openserverless-website` into `github.com/sciabarracom/openserverless-website`
should we replace "sciabarracom" with \<github-username\> or \<username\>?

2024-07-07 09:42 UTC, sciabarracom approved these changes

2024-07-07 09:42 UTC, merged